<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Имя проекта</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="#">Главная</a></li>
                    <li><a href="#">Ссылка</a></li>
                    <li><a href="#">Ссылка</a></li>
                    <li><a href="#">Ссылка</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Выпадающий список <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Действие</a></li>
                            <li><a href="#">Другое действие</a></li>
                            <li><a href="#">Еще и еще</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">Заголовок</li>
                            <li><a href="#">Ссылка</a></li>
                            <li><a href="#">Еще одна ссылка</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-search pull-left" action="">
                    <input type="text" class="search-query span2" placeholder="Поиск">
                </form>
                <ul class="nav pull-right">
                    <li><a href="#">Ссылка</a></li>
                    <li class="divider-vertical"></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Выпадающий список <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Действие</a></li>
                            <li><a href="#">Другое действие</a></li>
                            <li><a href="#">Еще и еще</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">Заголовок</li>
                            <li><a href="#">Ссылка</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.nav-collapse -->
        </div>
    </div><!-- /navbar-inner -->
</div>