<form id="addItem" action="<?php echo $this->controllerUrl; ?>/save">
    <div class="input-prepend">
        <span id="itemName" title="Required field" class="add-on" style="text-shadow:none;width:100px;background-color:#5F7181;border-color:#5F7181;color:#fff">Name: </span>
        <input name="itemName" style="width:400px" type="text" value="">
    </div>
    <div class="input-prepend">
        <span id="itemParent" class="add-on" style="text-shadow:none;width:100px;background-color:#5F7181;border-color:#5F7181;color:#fff">Parent name: </span>
        <select class="span3" style="width:400px;" name="itemParentId">
            <?php echo $this->groupSelect;?>
        </select>
    </div>
    <div class="input-prepend">
        <span id="itemType" class="add-on" style="text-shadow:none;width:100px;background-color:#5F7181;border-color:#5F7181;color:#fff">Type: </span>
        <select name="itemTypeId" style="width:150px;" class="span3">
            <option value="2">Item</option>
            <option value="1">Group</option>
        </select>
    </div>
    <div class="input-prepend">
        <span class="add-on" style="width:100px;height: 150px">Description: </span>
        <textarea name="itemDesc" id="textarea" style="width:400px;height:150px"></textarea>
    </div>
    <div id="result"></div>

    <button id="submitButton" type="button" class="btn btn-primary">Save item</button>
    <button id="closeButton" type="button" class="btn btn-primary">Close</button></a>
</form>

<script>
    /* attach a submit handler to the form */
    $(document).ready(function() {
        $("#submitButton").click(function(event) {
                event.preventDefault();
                if(!$('[name=itemName]').val()) {
                    $('#result').append('<div class="alert alert-error"><strong>Name</strong> is required</div>');
                }
                else {
                    $.post( $("#addItem").attr('action'), $("#addItem").serialize(),
                            function( data ) {
                                $( "#result" ).empty().append( data );
                            }
                    );
                    return false;
                }
            }
        );
        $("#closeButton").on("click",function(event) {
               $('#list').load($('#listTab').attr("href"));
            }
        );
    });
</script>