<button class="btn btn-info" style="margin-bottom: 10px" href="<?php echo $this->controllerUrl; ?>/add" id="addNewItem">Add new item</button>
<button class="btn btn-info" style="margin-bottom: 10px" href="<?php echo $this->controllerUrl; ?>/file" id="addNewFile">Add new file</button>

<div id='divContainer' style="position: absolute;"></div>

<table style="width:1000px" class="table table-striped table-bordered table-condensed">
    <?php echo $this->itemTree; ?>
</table>

<script>
    $(document).ready(function() {
        $("#addNewItem").click(function(event) {
                    $('#divContainer').load($('#addNewItem').attr("href"),
                            function() {$('#divContainer').addClass('well');}
                    );
                }
        );
        $("#addNewFile").click(function(event) {
                    $('#divContainer').load($('#addNewFile').attr("href"),
                            function() {$('#divContainer').addClass('well');}
                    );
                }
        );
    });
</script>


