<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title><?php echo $this->pageTitle; ?></title>
    <!-- Le styles -->
    <link href="<?php echo $this->baseUrl; ?>/htdocs/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $this->baseUrl; ?>/htdocs/css/bootstrap-responsive.css" rel="stylesheet">
    <!--link href="assets/js/google-code-prettify/prettify.css" rel="stylesheet" -->

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="<?php echo $this->baseUrl; ?>/htdocs/js/jquery.form.js"></script>
    <script src="<?php echo $this->baseUrl; ?>/htdocs/js/bootstrap.js"></script>
    <script src="http://bootstrap.veliovgroup.com/assets/js/bootstrap-tooltip.js"></script>

</head>
<body data-spy="scroll" data-target=".subnav" data-offset="50">
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="<?php echo $this->baseUrl; ?>">WebRobotics</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li <?php if($this->onlineTabActive) echo 'class="active"'; ?>>
                        <a href="<?php echo $this->baseUrl; ?>/online">Online board</a>
                    </li>
                    <li><a href="task">Tasks</a></li>
                    <li><a href="report">Reports</a></li>
                    <li><a href="suite">Test Suits</a></li>
                    <li <?php if($this->functionalityTabActive) echo 'class="active"'; ?>>
                        <a href="<?php echo $this->baseUrl; ?>/item">Product functionality</a>
                    </li>
                    <li style="margin-left: 20px">&nbsp;</li>
                    <li><a href="suite">Unit Tests</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>
<br>

<div class="container">
    <hr>
    <?php echo $this->layout()->content; ?>
    <footer>
    </footer>
</div> <!-- /container -->

</body>
</html>


